name: Build and Test

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies (Mise + Tuist)
        uses: jdx/mise-action@v2

      - name: Ensure Tuist Version is Pinned
        run: mise use --pin tuist

      - name: Debug Tuist Installation
        run: tuist --version

      - name: Debug Available Test Targets
        run: tuist test --list-targets

      - name: Run Tests
        run: |
          set -o pipefail
          tuist test RailMapiOSTests --verbose | xcbeautify --renderer github-actions
