name: Build and Test

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - all

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Tuist & Dependencies
        uses: jdx/mise-action@v2

      - name: Install Tuist
        run: |
          curl -Ls https://install.tuist.io | bash
          echo "$HOME/.tuist/bin" >> $GITHUB_PATH

      - name: Debug Tuist Targets
        run: tuist test --list-targets

      - name: Run Tests
        run: |
          set -o pipefail
          tuist test RailMapiOSTests | xcbeautify --renderer github-actions

      - name: Show Xcode Logs if Test Fails
        if: failure()
        run: cat ~/Library/Logs/DiagnosticReports/xcodebuild*.log || true
