name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: macos-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
      SDKROOT: /Applications/Xcode_16.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk
      
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest

  build-and-test:
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Verify Xcode and SDK
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version
          xcrun --sdk iphoneos --show-sdk-path

      - uses: swift-actions/setup-swift@v2
        with:
         swift-version: "6.0"

      - name: Verify Swift Version
        run: swift --version

      - name: Install Dependencies (Mise + Tuist)
        uses: jdx/mise-action@v2

      - name: Ensure Tuist Version is Pinned
        run: mise use --pin tuist

      - name: Build Project
        run: |
          export TUIST_SDK_OVERRIDE=iphoneos18.0
          tuist build

      - name: Run Tests
        run: tuist test --test-targets RailMapiOSTests
