name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install mise and Tuist
        run: |
          brew install mise
          mise plugin add tuist
          mise install tuist@latest
          mise use -g tuist@latest
        env:
          PATH: $HOME/.local/share/mise/shims:$PATH

      - name: Setup PATH for mise
        run: echo 'export PATH="$HOME/.local/share/mise/shims:$PATH"' >> $GITHUB_ENV

      - name: Reload environment
        run: source $GITHUB_ENV

      - name: Generate Xcode project with Tuist
        run: |
          tuist fetch
          tuist generate --no-open

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            clean test \
            -scheme RailMapiOSTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12' | xcpretty
