name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - run: tuist test RailMapiOSTests | xcbeautify --renderer github-actions
