name: Run Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install rtx and Tuist
        run: |
          brew install rtx
          rtx plugin add tuist
          rtx install tuist@latest
          rtx use -g tuist@latest

      - name: Generate Xcode project with Tuist
        run: |
          tuist fetch
          tuist generate --no-open

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            clean test \
            -scheme RailMapiOSTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12' | xcpretty
