name: Run Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Install Tuist
        run: |
          curl -Ls https://install.tuist.io | bash

      - name: Generate Xcode project with Tuist
        run: |
          tuist fetch
          tuist generate --no-open

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -scheme <SchemeName> # Remplace <SchemeName> par le vrai nom de ton scheme

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            clean test \
            -scheme <SchemeName> \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12' | xcpretty
